pinpoint-apm/go-aop-agent

libs/httpClient/go.mod
libs/mongo/go.mod
libs/pinpointEtcd/go.mod
libs/redisv8/go.mod
libs/sql/go.mod
middleware/echo/go.mod
middleware/echoV4/go.mod
middleware/mux/go.mod
testapps/echo/go.mod
testapps/mux/go.mod

refactor(update-v1.0.0): v0.0.1 is removed

---

README.md
version.go

* libs use the latest version
* "v1.0.1" missing

no download for libs

---

libs/httpClient/go.mod
libs/httpClient/go.sum
libs/mongo/go.mod
libs/mongo/go.sum
libs/pinpointEtcd/go.mod
libs/pinpointEtcd/go.sum
libs/redisv8/go.mod
libs/redisv8/go.sum
libs/sql/go.mod
libs/sql/go.sum
libs/transport/go.mod
libs/transport/go.sum
middleware/echo/go.mod
middleware/echo/go.sum
middleware/echoV4/go.mod
middleware/echoV4/go.sum
middleware/micro/go.mod
middleware/micro/go.sum
middleware/mux/go.mod
middleware/mux/go.sum
testapps/echo/go.mod
testapps/mux/go.mod

update v1.0.1 to v1.0.2
* libs
* middleware

refactor: version id

---

.github/workflows/libraries-test.yml
.github/workflows/main.yml
aop/pinpoint.go
aop/pinpoint_test.go
common/pinpointCommon.go
libs/httpClient/go.mod
libs/mongo/go.mod
libs/pinpointEtcd/go.mod
libs/redisv8/go.mod
libs/sql/go.mod
libs/transport/go.mod
middleware/echo/echoMiddleware.go
middleware/echo/go.mod
middleware/echoV4/echoMiddlewareV4.go
middleware/echoV4/go.mod
middleware/micro/go.mod
middleware/micro/microWrapper.go
middleware/mux/go.mod
middleware/mux/muxMiddleware.go
testapps/echo/go.mod
testapps/mux/go.mod
version.go

check FORCE_DISABLE_PINPOINT_AGENT env
* split build.yml into aop and libraries

feat: force disable

---

libs/httpClient/go.sum
libs/mongo/go.sum
libs/pinpointEtcd/go.sum
libs/redisv8/go.sum
libs/sql/go.sum
libs/transport/go.sum
middleware/echo/go.sum
middleware/echoV4/go.sum
middleware/micro/go.sum
middleware/mux/go.sum

refactor: update go sum

---

.github/workflows/libraries-test.yml

fix: ci failed

---

.github/workflows/libraries-test.yml
README.md

test: auto commit

---

aop/pinpoint.c
libs/redisv8/hookAndTrampoline.go

* ppRedisHook: include `DB `
* enable `PP_ADD_EXCEPTION`

Feat pp redis

---

README.md
common/trace.go
common/trace_test.go

* add PinCallFunc
* rename PinTranscation

[ENH] PinCallFunc

---

common/api_test.go
common/pinpointCommon.go
common/trace.go
libs/redisv8/hookAndTrampoline.go

* [[fix] long size](https://github.com/pinpoint-apm/go-aop-agent/commit/cdc515e1080ff0edd432e109e54ce8f95d17353f)
* [[style] rename TRACE_ID_TYPE](https://github.com/pinpoint-apm/go-aop-agent/commit/d6ec947f8e0ee61c85f4610f7e7c4a1478114444)
* [[enh] enable wakeTrace](https://github.com/pinpoint-apm/go-aop-agent/commit/07616afc8eb58c6173f457aa5cbfa6893d6388f7)

cumulative update

---

common/trace.go
common/trace_test.go

* trace user HttpClient function
* fix init_test

[enh] add PinHttpClientFunc/testcase

---

common/trace.go

append addClueSFunc(PP_ARGS, remoteUrl)

[enh] httpClient add args

---

common/trace.go

* remove PP_ARGS
* shared PP_HTTP_URL

[enh] httpclient add path

---

libs/httpClient/go.mod
libs/httpClient/go.sum
libs/mongo/go.mod
libs/mongo/go.sum
libs/redisv8/go.mod
libs/redisv8/go.sum
libs/sql/go.mod
libs/sql/go.sum
libs/transport/go.mod
libs/transport/go.sum
middleware/echo/go.mod
middleware/echo/go.sum
middleware/echoV4/go.mod
middleware/echoV4/go.sum
middleware/micro/go.mod
middleware/micro/go.sum
middleware/mux/go.mod
middleware/mux/go.sum

[style] update to v1.0.4

---

common/api_test.go
common/pinpointCommon.go

* add Pinpoint_start_trace_opt and testcase

[feat] Pinpoint_start_trace_opt

---

common/trace.go
common/trace_test.go

> support Pinpoint_start_trace_opt API

[enh] PinHttpClientFunc

---

version.go

[style] v1.0.3 ->v1.0.5

---

.github/workflows/update-libs.yml

remove needs

---

common/trace.go

[enh]  tidy trace flow

---

common/api_test.go
common/pinpointCommon.go

* from pinpoint-c-agent  https://github.com/pinpoint-apm/pinpoint-c-agent/issues/448

[enh] show_status

---

.github/workflows/update-libs.yml

[build] tidy the mod when update

---

common/api_test.go
common/pinpointCommon.go
common/trace_test.go

* version 0.4.41
* BenchmarkSetlong
* update Pinpoint_get_int_context API

[build] update to v0.4.14

---

common/api_test.go
common/pinpointCommon.go

SetLogCallBack
* remove PINPOINT_LOG_ENABLE checking

[enh] callback for library output

---

common/api_test.go
common/pinpointCommon.go
common/trace.go

* parentId== -1
* add PP_NEXT_SPAN_ID

[fix] check parentId

---

common/api_test.go
common/pinpointCommon.go

[test] add Prerequisite
